// Sayma (Counting) — düzey zenginleştirmesi (Clements & Sarama)
// trajectories.data.js CORE içindeki "count" yörüngesinin 19 düzeyini
// öğretmen/veli için derinleştirir. Altın-standart şablon: yorunge.enrich.js (sub).
// Her düzey: how (nasıl görünür) · teacher (öğretmen notu) · act (etkinlik) ·
// viz (opsiyonel görsel reçetesi) · tool (opsiyonel DokunSay aracı; varsayılan "bar").
export default [
  { // 0 — Sayı Sözcüğü Söyleyici: Temeller (0–12 ay)
    how: "Bebek, ninniyle \"bir iki üç\" söylerken sesleri yakalar; kendi ezberlemesinden bağımsız sözcükleri mırıldanır ya da ritme katılır. Henüz sözcükler nesneye bağlı değildir; sesin ezgisini yaşar.",
    teacher: "Bu, sayı dilinin işitsel tohumudur: çocuk anlamı değil, sayı sözcüklerinin sesini ve sırasını içselleştirmeye başlar. Parmak oyunları, sayışmacalar ve günlük \"bir, iki, hop!\" gibi ritimler bu erken sesletimi besler. Amaç saymak değil, sayı sözcüklerini tanıdık kılmaktır.",
    act: {
      materials: ["sayışmacalı bir tekerleme veya parmak oyunu", "kucakta sallama/zıplatma ritmi"],
      steps: [
        "Çocuğu kucağınıza alıp \"bir, iki, üç\" diyerek nazikçe zıplatın.",
        "Her sayıda sesi belirginleştirin, göz teması kurun.",
        "Parmaklarını birer birer dokundurarak \"bir… iki…\" söyleyin.",
        "Günün farklı anlarında (merdiven, mama) aynı sayışı yineleyin.",
      ],
      criterion: "Sayışlı ritme sesle/hareketle katılır ya da sayı seslerini taklit etmeye çalışırsa ✓",
      easy: "Tek bir kısa tekerlemeye sadık kalın, abartılı tonlama kullanın.",
      hard: "Sayışı 5'e dek uzatın, çocuğun bir sözcüğü tamamlamasını bekleyin.",
    },
  },
  { // 1 — Ezbere Sayan (24–36 ay)
    how: "Çocuk \"bir iki üç beş altı…\" gibi sayı dizisini söyler ama bazı sayıları atlar ya da sırayı karıştırır. Sözcükler çoğu zaman akıcı bir şarkı gibi akar, henüz nesneleri saymaz.",
    teacher: "Bu, kararlı sıra ilkesinin filizlenmesidir: çocuk sayı sözcüklerini bir dizi olarak öğrenir, ama dizi henüz eksiksiz ve değişmez değildir. Atlanan/karışan sayılar normaldir; bol bol birlikte sayarak doğru sırayı modelleyin. Bu aşamada amaç ezber dizisini uzatmak ve sağlamlaştırmaktır.",
    act: {
      materials: ["DokunSay pulları (bir kabın içinde)", "ritimli birlikte sayma fırsatları (merdiven, adım)"],
      steps: [
        "Pulları kaba atarken yüksek sesle birlikte sayın: \"bir, iki, üç…\".",
        "Çocuk sizinle aynı anda söylesin; siz biraz önden gidin.",
        "Bir sayıyı atlarsa durmayın; turun sonunda doğrusunu yavaşça yineleyin.",
        "Her gün birkaç kez kısa sayışlar yapın (basamak, oyuncak toplama).",
      ],
      criterion: "En az 1'den 5'e kadar (küçük atlamalarla da olsa) ezbere sayarsa ✓",
      easy: "1'den 3'e dek tutun; siz söyleyin, o tekrarlasın.",
      hard: "Diziyi 10'a doğru uzatın, çocuk tek başına başlasın.",
    },
    viz: { t: "count", n: 5 },
  },
  { // 2 — Ezbere Sayan (10) (36–42 ay)
    how: "Çocuk \"bir, iki, üç… on\" diye 1'den 10'a kadar doğru sırayla, atlamadan sayar. Bu artık güvenilir bir ezber dizisidir; nesne olmadan da akıcıdır.",
    teacher: "Kararlı sıra burada 10'a dek oturur — sonraki tüm sayma becerilerinin sözel iskeleti budur. Dizi sağlam olmadan birebir eşleme ve sayma kurulamaz. \"Ondan sonra ne gelir?\" gibi sorularla diziyi esnetin; geriye doğru değil, ileriye akıcılığı hedefleyin.",
    act: {
      materials: ["DokunSay pulları veya çubukları", "10'a dek sayı şarkısı/tekerlemesi"],
      steps: [
        "Birlikte 1'den 10'a sayın; sonra çocuk yalnız denesin.",
        "Takıldığı sayıdan önceki sayıyı fısıldayarak ipucu verin.",
        "\"Beşten sonra hangisi gelir?\" gibi tek-adım sorular sorun.",
        "Pulları onar onar bir sıraya dizerken her birine bir sayı söyleyin.",
      ],
      criterion: "1'den 10'a kadar duraksamadan, doğru sırayla ve atlamadan sayarsa ✓",
      easy: "Önce 1–5 sağlamlaşsın; sonra 6–10'u ekleyin.",
      hard: "\"Üçten başlayıp ona kadar say\" gibi farklı başlangıçlar isteyin.",
    },
    viz: { t: "tenframe", n: 10, frames: 1 },
  },
  { // 3 — Birebir Eşleyen (36–48 ay) ★ DARBOĞAZ
    how: "Çocuk her nesneye dokunurken tam bir sayı sözcüğü söyler: el ve dil aynı ritimde gider. Henüz oturmamışsa parmağı nesnelerden hızlı geçip sözcükler geride kalır ya da bir nesneye iki kez \"iki, üç\" der.",
    teacher: "Birebir eşleme saymanın ilk gerçek darboğazıdır: çocuk sayı dizisini bilse bile her sözcüğü tam bir nesneye denk getiremezse sayım bozulur. Bu eşlemede süreğen güçlük, matematik öğrenme güçlüğü (diskalkuli) açısından erken bir uyarı işaretidir — tipik gelişende dokun-say senkronu bu yaşta kurulur. Çocuğun parmağını her pula bastırarak \"dokun-söyle\" ritmini birlikte kurun; hızı düşürün, nesneleri tek sıraya dizin ki atlama/tekrar görünür olsun.",
    act: {
      materials: ["DokunSay pulları (tek sıraya dizili)", "parmakla itmek için küçük bir tepsi/oluk", "sayılan-sayılmayan ayrımı için bir çizgi/ayraç"],
      steps: [
        "Pulları tek sıraya dizin; çocuk her pula dokunarak \"bir, iki, üç…\" desin.",
        "Her dokunuşta pulu hafifçe öteye itsin (sayılanı ayırsın).",
        "Çok hızlıysa elini tutup ritmi yavaşlatın: dokun-söyle, dokun-söyle.",
        "Bir nesneyi atlar/iki kez sayarsa durdurup birlikte o noktadan yineleyin.",
      ],
      criterion: "3–5 nesneyi her birine bir (yalnız bir) sözcük denk gelecek şekilde dokunarak senkron sayarsa ✓",
      easy: "2–3 büyük pulla, aralarını açarak çalışın; siz parmağını yönlendirin.",
      hard: "Pulları daire/dağınık dizin (başlangıcı işaretlemeden) ya da 6–8'e çıkın.",
    },
    viz: { t: "count", n: 5 },
    tool: "bar",
  },
  { // 4 — Sayan (Küçük Sayılar) (48–54 ay) ★ DARBOĞAZ
    how: "Çocuk 4 pulu sayar ve \"Kaç tane?\" sorulduğunda saydığı SON sözcüğü (\"dört\") yineleyerek bütünün çokluğunu söyler. Henüz oturmamışsa tüm diziyi baştan tekrar sayar (\"bir-iki-üç-dört\") ama \"kaç\" sorusuna sayı vermez.",
    teacher: "Burada kardinalite ilkesi devreye girer: saymanın amacı son sözcüğün TÜM kümeyi temsil ettiğini kavramaktır. Bu sıçramayı yapamamak — doğru sayıp da \"kaç?\" sorusuna yeniden saymakla yanıt vermek — matematik öğrenme güçlüğü (diskalkuli) için klasik bir erken belirtidir; çünkü sayı sözcüğü henüz \"miktar\" anlamına bağlanmamıştır. Saydırdıktan sonra kümeyi elinizle çevreleyip \"yani toplam DÖRT\" diyerek son sözcüğü bütünle özdeşleştirin; pulları sayıp avucunuza alın, \"hepsi kaç?\" deyin.",
    act: {
      materials: ["DokunSay pulları (3–5'lik kümeler)", "kümeyi çevrelemek için küçük bir halka/tabak", "kapatma kartı"],
      steps: [
        "Çocuk 4 pulu birebir saysın.",
        "Hemen \"Peki hepsi kaç tane?\" diye sorun; yeniden sayarsa \"saymadan, son söylediğin sayı kaçtı?\" diye yönlendirin.",
        "Kümeyi halkayla çevreleyip \"dört pul — toplam dört\" deyin.",
        "Sayılan pulları kapatıp \"şimdi kaç vardı?\" diye sorun (görmeden hatırlasın).",
      ],
      criterion: "Saydıktan sonra \"kaç?\" sorusuna yeniden saymadan, son sayıyı söyleyerek (kardinalite) yanıt verirse ✓",
      easy: "2–3'lük kümelerle çalışın; siz sayın, çocuk yalnız \"kaç?\"ı söylesin.",
      hard: "5–6'ya çıkın; saydıktan sonra bir pul ekleyip \"şimdi kaç?\" deyin (yeniden saymadan +1).",
    },
    viz: { t: "count", n: 4 },
    tool: "bar",
  },
  { // 5 — Sayan (10) (54–60 ay)
    how: "Çocuk 10'a kadar olan bir nesne kümesini tek tek dokunarak güvenle sayar ve son sayıyı çokluk olarak verir. Atlamadan, tekrarlamadan; daha büyük kümelerde bile sayım düzenlidir.",
    teacher: "Birebir eşleme ve kardinalite artık 10'a dek bütünleşmiştir. Bu, sağlam bir sayma temelidir; çocuk artık dağınık dizilimlerde de sayımı yönetebilmelidir. Sayılanı sayılmayandan ayırma stratejisini (itme, sıraya dizme) pekiştirin ki büyük kümelerde hata azalsın.",
    act: {
      materials: ["DokunSay pulları (6–10'luk kümeler)", "sayılanları ayırmak için bir tepsi/oluk"],
      steps: [
        "8 pulu dağınık koyun; çocuk her birine dokunup saysın, sayılanı kenara itsin.",
        "\"Kaç tane?\" diye sorun, son sayıyı çokluk olarak söylesin.",
        "Pulları yeniden karıştırıp \"yine kaç?\" deyin (sayı değişmez).",
        "10'a dek farklı kümelerle yineleyin.",
      ],
      criterion: "10'a kadar bir kümeyi atlamadan/tekrarlamadan sayıp çokluğu doğru söylerse ✓",
      easy: "Pulları tek sıraya dizin; 6–7 ile sınırlayın.",
      hard: "Dağınık 9–10; sayım sırasında kümeyi hafifçe oynatın.",
    },
    viz: { t: "tenframe", n: 10, frames: 1 },
    tool: "bar",
  },
  { // 6 — Üretici (Küçük Sayılar) (54–60 ay)
    how: "\"Bana 6 pul ver\" dediğinizde çocuk yığından sayarak tam 6 tane ayırır ve durur. Tanımanın ötesine geçip istenen çokluğu kendisi ÜRETİR; son pulu verince doğal olarak durması kardinaliteyi kullandığını gösterir.",
    teacher: "Bu, kardinalitenin tersine işlemesidir: çocuk artık yalnız sayıp çokluğu söylemekle kalmaz, verilen sayıya ulaşınca durmayı bilir (\"say-ve-dur\"). İstenen sayıya gelince durmuyor, yığının tamamını veriyorsa hedef sayıyı zihinde tutamıyordur — sayarken hedefi yüksek sesle hatırlatın. Bu beceri toplama-çıkarmanın ön koşuludur.",
    act: {
      materials: ["DokunSay pulları (bol bir yığın)", "verilenleri koymak için küçük bir tabak"],
      steps: [
        "Yığını ortaya koyun: \"Bana 5 pul ver.\"",
        "Çocuk sayarak alsın; 5'e gelince durup tabağa koysun.",
        "Birlikte sayarak doğrulayın: \"bir-iki-üç-dört-beş, evet beş!\".",
        "Farklı sayılar isteyin (3, 6, 4); her seferinde durduğu yeri gözleyin.",
      ],
      criterion: "İstenen küçük çokluğu (3–6) sayarak üretip doğru sayıda durup verirse ✓",
      easy: "Önce 2–3 isteyin; hedef sayıyı siz birlikte sayın.",
      hard: "\"6 ver, sonra 2 daha ekle — şimdi kaç?\" gibi üretip-genişletin.",
    },
    viz: { t: "count", n: 6 },
    tool: "bar",
  },
  { // 7 — Sayan ve Üretici (10+) (60–66 ay)
    how: "Çocuk 10 ve üzerindeki kümeleri (12, 15) güvenle sayar ve \"bana 13 pul ver\" gibi istekleri sayarak karşılar. On sınırını aşan sayı sözcüklerini (on bir, on iki…) sayımına sorunsuz katar.",
    teacher: "Sayma artık onluk eşiğini aşar; bu, 1'er 1'er 100'e giden yolun başıdır. Onlu sayı sözcüklerinin düzensizliği (on bir, on iki) takılmaya yol açabilir — bu geçişleri bol bol modelleyin. Hem sayma (oku) hem üretme (yap) yönünü birlikte çalıştırın ki beceri çift yönlü sağlamlaşsın.",
    act: {
      materials: ["DokunSay pulları/çubukları (15+ pul)", "sayılanları dizmek için sıra/oluk"],
      steps: [
        "13 pulu tek sıraya dizip çocuk saysın; on'dan sonra \"on bir, on iki…\" geçişini birlikte söyleyin.",
        "\"Kaç tane?\" diye çokluğu sorun.",
        "Sonra tersini isteyin: \"bana 12 pul ver.\"",
        "10–15 arası farklı sayılarla say-ve-üret turları yapın.",
      ],
      criterion: "10–15 arası bir kümeyi doğru sayar VE istenen sayıyı sayarak üretirse ✓",
      easy: "10–12 ile sınırlı tutun; onlu sözcükleri siz başlatın.",
      hard: "16–20'ye çıkın; sayım sırasında bir pul gizleyip \"kaç eksildi?\" deyin.",
    },
    viz: { t: "tenframe", n: 14, frames: 2 },
    tool: "bar",
  },
  { // 8 — 10'dan Geriye Sayan (66–72 ay) ★ DARBOĞAZ
    how: "Çocuk \"on, dokuz, sekiz… bir\" diye 10'dan geriye akıcı sayar. Henüz oturmamışsa her geri adımda durup ileriye sayarak hangi sayının geldiğini bulmaya çalışır ya da sırayı karıştırır.",
    teacher: "Geriye sayma gerçek bir darboğazdır: ileri sayı dizisi ezberle gelir, ama geriye saymak diziyi zihinde TERS yönde işletmeyi gerektirir — bu, çıkarmanın ve \"geriye sayarak\" stratejisinin doğrudan zeminidir. Roket geri sayımı gibi anlamlı bir bağlam kullanın; her sayıda bir pulu sıradan geri alarak çokluğun azalışını görünür kılın. Akıcılık değil, önce doğru sıra hedeftir.",
    act: {
      materials: ["DokunSay pulları (10'luk bir sıra)", "geri sayım için \"roket/asansör\" bağlamı", "sayı doğrusu şeridi (0–10)"],
      steps: [
        "10 pulu sıraya dizin: \"Roket kalkıyor, geriye sayalım!\".",
        "Her sayıda en sondaki pulu birlikte geri alın: \"on… dokuz… sekiz…\".",
        "Çocuk takılırsa o noktadan ileriye sayıp doğru sayıyı bulun, sonra geriye devam edin.",
        "Sayı doğrusunda parmağı sağdan sola kaydırarak eşlik ettirin.",
      ],
      criterion: "10'dan 1'e (veya 0'a) kadar duraksamadan, doğru sırayla geriye sayarsa ✓",
      easy: "5'ten geriye başlayın; pulları geri alarak somutlaştırın.",
      hard: "\"7'den geriye say\" gibi farklı sayıdan başlatın ya da 20'den geriye deneyin.",
    },
    viz: { t: "numline", max: 10, at: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0], hi: 10 },
    tool: "bar",
  },
  { // 9 — N'den Sayan (N+1, N−1) (72–78 ay)
    how: "Çocuğa \"yedi\" deyip \"bundan sonra say\" dediğinizde baştan başlamadan \"sekiz, dokuz, on…\" diye devam eder; \"bundan önce?\" deyince \"altı\" der. Sayma artık herhangi bir çıpadan başlayabilir.",
    teacher: "Bu, sıra-bağımsız sayma esnekliğidir: çocuk artık her sayışa 1'den başlamak zorunda değildir, herhangi bir sayıyı çıpa alıp ileri/geri gidebilir. Bu beceri \"sayarak ilerleme\" (counting on) stratejisinin kalbidir ve toplama-çıkarmayı verimli kılar. Verilen sayıyı tekrar saymadan hemen sonrakini söylemesi (\"yedi → sekiz\") asıl kazanımdır.",
    act: {
      materials: ["DokunSay pulları", "sayı kartları (5–15)", "sayı doğrusu şeridi (0–15)"],
      steps: [
        "Bir sayı kartı gösterin (ör. 7): \"Buradan ileri say.\"",
        "Çocuk 1'den başlarsa \"yediyi biliyoruz, hemen sonrası?\" diye yönlendirin.",
        "\"Bundan bir önce hangisi?\" diye N−1'i sorun.",
        "Sayı doğrusunda verilen noktadan ileri/geri birer adım attırın.",
      ],
      criterion: "Verilen bir sayıdan (1'e dönmeden) ileri sayar ve bir önceki/sonraki sayıyı doğru söylerse ✓",
      easy: "Küçük çıpalardan (3, 4) başlayın; yalnız N+1 isteyin.",
      hard: "Onluk geçiş içeren çıpalar (9→10, 19→20) ve N−1 birlikte.",
    },
    viz: { t: "numline", max: 12, at: [6, 7, 8, 9], hi: 7 },
    tool: "bar",
  },
  { // 10 — 100'e Onar Ritmik Sayan (78–84 ay)
    how: "Çocuk \"on, yirmi, otuz… yüz\" diye 10'ar 10'ar yüze sayar; onluk sözcüklerin ritmini bir tekerleme gibi akıtır. Onluk demetleri (10'luk çubuklar) sayarken bu ritim doğrudan işe yarar.",
    teacher: "Onar sayma, basamak değerine ve çarpımsal düşünmeye açılan kapıdır: çocuk 10'u tek bir birim (\"bir onluk\") gibi atlayarak sayar. Bunu somut onluk çubuklarla bağlayın — her \"on\" bir çubuğa denk gelsin — ki ritim anlamsız bir ezber kalmasın. Onar sayı dizisi, ileride çarpma tablolarının (özellikle 10'lar) temelini kurar.",
    act: {
      materials: ["DokunSay onluk çubukları (10'luk)", "onar sayı şeridi (10, 20, 30…)"],
      steps: [
        "Onluk çubukları birer birer dizerken birlikte sayın: \"on, yirmi, otuz…\".",
        "Her çubuğun \"bir onluk = on pul\" olduğunu vurgulayın.",
        "Çocuk yalnız 100'e dek onar saysın; takılırsa çubuğu gösterip ipucu verin.",
        "\"Yetmişten sonra hangisi gelir?\" gibi tek-adım sorular sorun.",
      ],
      criterion: "10'dan 100'e kadar 10'ar 10'ar, doğru sırayla ritmik sayarsa ✓",
      easy: "50'ye dek tutun; her onluğu çubukla eşleştirin.",
      hard: "\"Otuzdan başlayıp onar say\" ya da \"yüzden geriye onar say.\"",
    },
    viz: { t: "array", r: 2, c: 5 },
    tool: "bar",
  },
  { // 11 — 100'e Sayan (78–90 ay)
    how: "Çocuk 1'er 1'er 100'e kadar sayar; en kritik yer onluk geçişlerdir: \"…yirmi sekiz, yirmi dokuz, OTUZ\". Geçişte takılırsa \"yirmi on\" gibi yanlış üretir ya da bir sonraki onluğa atlayamaz.",
    teacher: "1'er 1'er 100'e saymanın asıl güçlüğü onluk dönüşlerdir (29→30, 39→40): çocuğun bir onluğun bittiğini ve yeni onluğun başladığını kavraması gerekir. Bu geçişleri özellikle çalıştırın; yüz tablosu (hundred chart) ile satır sonlarını görsel olarak işaretleyin. Onluk yapısını fark etmek, sonraki tüm basamak-değeri çalışmasının zeminidir.",
    act: {
      materials: ["yüz tablosu (1–100 ızgara)", "DokunSay pulları (geçişleri somutlamak için)"],
      steps: [
        "Yüz tablosunda parmakla ilerleyerek birlikte sayın.",
        "Satır sonuna (…29) gelince durup \"şimdi yeni onluk: otuz!\" deyin.",
        "Çocuk yalnız sayarken geçişlerde (39, 49) ipucu hazır bekleyin.",
        "Takıldığı onluğu pullarla (iki onluk + dokuz birlik → bir daha) somutlaştırın.",
      ],
      criterion: "1'den 100'e kadar, onluk geçişlerini (29→30 vb.) doğru yaparak sayarsa ✓",
      easy: "Önce 1–30 arası onluk geçişlere odaklanın.",
      hard: "Belirli bir onluktan (ör. 47'den) başlatıp 100'e saydırın.",
    },
    tool: "bar",
  },
  { // 12 — Örüntü Kullanarak İleri Sayan (84–96 ay)
    how: "Çocuk her onluğun içindeki örüntüyü (…1, …2, …3) fark ederek sayar: \"kırk bir, kırk iki…\" derken birler basamağının 1–9 tekrarını kullanır. Yeni bir onluğa geçince doğru onluk adını söyleyip aynı birler örüntüsünü sürdürür.",
    teacher: "Bu düzeyde sayma artık ezber değil, örüntü-temelli akıl yürütmedir: çocuk sayı sisteminin düzenli yapısını (her onlukta birler 1–9 tekrarlar) keşfeder. Bu içgörü, sayı doğrusu ve basamak değeri anlayışını güçlendirir. \"Elli üçten sonra ne gelir, neden?\" gibi sorularla örüntüyü dile döktürün; yüz tablosunun sütun/satır düzeni bu örüntüyü görünür kılar.",
    act: {
      materials: ["yüz tablosu (1–100)", "tek bir onluk şeridi (örn. 40–49 kartları)"],
      steps: [
        "Bir onluk şeridini gösterip \"birler basamağı nasıl gidiyor?\" diye sordurun (1,2,3…).",
        "\"Peki sıradaki onlukta da böyle mi?\" deyip elli'leri birlikte okuyun.",
        "Çocuk bir onluğun ortasından (ör. 56) devam etsin.",
        "\"Altmış dokuzdan sonra hangi onluk başlar?\" diye örüntüyü genelletin.",
      ],
      criterion: "Onluk içi 1–9 örüntüsünü kullanarak (ezberden değil) ileri sayar ve yeni onluğa geçişi açıklarsa ✓",
      easy: "Tek bir onlukta (40–49) örüntüyü pekiştirin.",
      hard: "Onluk tablosu olmadan, sözlü olarak farklı onluklardan başlatın.",
    },
    tool: "bar",
  },
  { // 13 — Ritmik Sayan (90–102 ay)
    how: "Çocuk \"iki, dört, altı…\", \"beş, on, on beş…\" ve \"on, yirmi, otuz…\" diye 2'şer, 5'er, 10'ar ritmik sayar; aradaki sayıları atlayıp yalnız basamak noktalarını söyler. Sayış bir ritim/şarkı düzeninde akar.",
    teacher: "Ritmik (atlamalı) sayma, çarpmanın ve eşit gruplamanın algısal temelidir: 2'şer saymak 2'nin katlarını, 5'er saymak 5'in katlarını üretir. Bunu eşit gruplarla (2'li pul demetleri, bir el = 5) bağlayın ki çocuk \"kaç grup × kaç\" ilişkisini sezsin. Dizi (array) düzeni, atladığı sayıların nereye gittiğini görünür kılar.",
    act: {
      materials: ["DokunSay pulları (2'li/5'li gruplara dizili)", "2×5 veya 2×n dizi düzeni", "el/parmak (5'er için)"],
      steps: [
        "Pulları ikişerli demetler hâlinde dizin: her demete dokunup \"iki, dört, altı…\" deyin.",
        "Elleri kullanarak \"beş, on, on beş…\" beşer sayın.",
        "Onluk çubuklarla \"on, yirmi…\" onar sayın.",
        "\"Altı, ikişer saysak kaçıncı adımda gelir?\" gibi bağ kurun.",
      ],
      criterion: "2'şer, 5'er ve 10'ar (en az ikisinde) doğru ve akıcı ritmik sayarsa ✓",
      easy: "Yalnız 10'ar ve 5'er ile başlayın; demetleri elle gösterin.",
      hard: "3'er saymayı ekleyin ya da bir sayıdan (ör. 6'dan ikişer) başlatın.",
    },
    viz: { t: "array", r: 2, c: 5 },
    tool: "bar",
  },
  { // 14 — Takip Ederek İleri Sayan (96–108 ay)
    how: "Çocuk \"yediden başla, dört ileri say\" dediğinizde \"sekiz-dokuz-on-on bir\" derken aynı anda KAÇ adım saydığını parmaklarıyla takip eder ve dördüncü adımda durur. İki şeyi birden izler: hangi sayıdayım ve kaç saydım.",
    teacher: "Bu, çift sayma (double counting) becerisidir ve sayarak toplamanın (counting on) tam hâlidir: çocuk hem sayı dizisini hem adım sayısını eşzamanlı izler. Parmaklar burada \"kaç adım\" sayacı olarak güçlü bir destektir. Kaç adım gittiğini takip edemezse fazla/eksik sayar — adımları parmakla somutlaştırmasını teşvik edin. Bu beceri, bilinmeyen-değişim problemlerini (7'den kaça? +4) çözmenin anahtarıdır.",
    act: {
      materials: ["DokunSay pulları", "adım saymak için parmaklar", "sayı doğrusu şeridi (0–20)"],
      steps: [
        "\"Yediden başla\" deyin; çocuk \"yedi\"yi yumruğunda tutsun.",
        "\"Dört ileri say\" deyin; her sayıda bir parmak açsın: sekiz(1), dokuz(2), on(3), on bir(4).",
        "Dört parmak açılınca dursun: \"Nerede bitti?\" → on bir.",
        "Sayı doğrusunda 7'den 4 sıçrama yaptırıp ulaştığı sayıyı okutun.",
      ],
      criterion: "Bir sayıdan verilen adım kadar ileri sayıp, adım sayısını takip ederek doğru sayıda durursa ✓",
      easy: "Az adımla (2–3) ve küçük başlangıçla; siz parmakları birlikte açın.",
      hard: "Onluk geçişli (8'den 5 ileri) ya da geriye doğru adım sayımı (12'den 3 geri).",
    },
    viz: { t: "numline", max: 14, at: [7, 8, 9, 10, 11], hi: 11 },
    tool: "bar",
  },
  { // 15 — Niceliksel Birim / Basamak Değeri Sayıcısı (102–114 ay)
    how: "Çocuk 34'ü sayarken \"otuz (üç onluk)… kırk, kırk bir, kırk iki\" gibi onluk ve birlik birimleri birlikte kullanır; onluk çubuklarla birlik küpleri bir arada sayıp \"üç onluk dört birlik, otuz dört\" der. Onluğu tek tek değil, demet olarak sayar.",
    teacher: "Bu, basamak değerinin sayma içine yerleşmesidir: çocuk artık onluğu bir birim (on'luk) olarak sayar, birlikleri ayrı izler. DokunSay Basamak aracı (onluk çubuk + birlik küp) bu düzeyi doğrudan besler. \"Üç onluk kaç eder?\" → \"otuz\" zincirini kurun; onlukları onar sayıp kalan birlikleri birer ekleyerek karışık birimle saymayı modelleyin. Bu, çok basamaklı sayma ve toplamanın kalbidir.",
    act: {
      materials: ["DokunSay Basamak blokları (onluk çubuk + birlik küp)", "2 basamaklı sayı kartları"],
      steps: [
        "3 onluk çubuk + 4 birlik küp koyun: \"Önce onlukları say, sonra birlikleri ekle.\"",
        "Çocuk \"on, yirmi, otuz — otuz bir, otuz iki, otuz üç, otuz dört\" desin.",
        "\"Kaç onluk, kaç birlik?\" diye yapıyı söyletin (3 onluk, 4 birlik).",
        "Yazılı 34'ü blok düzenine eşleştirin; bir onluk daha ekleyip yeniden saydırın.",
      ],
      criterion: "Onluk ve birlik birimleri bir arada kullanarak iki basamaklı bir sayıyı (ör. 34) doğru sayar ve yapısını (kaç onluk/birlik) söylerse ✓",
      easy: "Birlikleri azaltın (3 onluk + 2 birlik); önce yalnız onlukları onar saydırın.",
      hard: "Yüzlük levha ekleyip 3 basamağa geçin ya da onluk bozarak (üç onluk = yirmi on) saydırın.",
    },
    viz: { t: "baseten", tens: 3, ones: 4 },
    tool: "basamak",
  },
  { // 16 — 100 Ötesine Sayan (108–120 ay)
    how: "Çocuk \"…doksan sekiz, doksan dokuz, YÜZ, yüz bir, yüz iki…\" diye 100'ün ötesine geçer; en kritik yer yüzlük ve onluk geçişlerin üst üste bindiği yerlerdir (109→110, 199→200). Yüzler basamağını sayıma katarak akışı sürdürür.",
    teacher: "100'ü aşmak, sayı sisteminin örüntüsünün yüzler basamağında da tekrarladığını kavramayı gerektirir: 100'den sonra 1–99 örüntüsü baştan döner. Çoklu geçişler (199→200: hem onluk hem yüzlük döner) en zorlandığı yerlerdir; bunları özellikle çalıştırın. Bu beceri, büyük sayılarda basamak değeri yapısının genellenmesidir.",
    act: {
      materials: ["DokunSay Basamak blokları (yüzlük levha + onluk + birlik)", "100–130 sayı şeridi"],
      steps: [
        "Bir yüzlük levha gösterip \"bu yüz\" deyin; üstüne onluk/birlik ekleyerek saydırın.",
        "98, 99'dan başlatıp \"yüz\" geçişini birlikte vurgulayın.",
        "Çoklu geçişleri (109→110, 119→120) ayrıca çalıştırın.",
        "\"Yüz doksan dokuzdan sonra ne gelir?\" gibi çift-dönüş sorular sorun.",
      ],
      criterion: "100'ün ötesine, yüzlük/onluk geçişlerini (109→110, 199→200 vb.) doğru yaparak sayarsa ✓",
      easy: "100–120 arası tek geçişlere odaklanın.",
      hard: "200'e dek saydırın ya da 100'den onar/yüzer ileri saydırın.",
    },
    tool: "basamak",
  },
  { // 17 — Sayı Korunumunu Kavrayan (108–120 ay)
    how: "Çocuk 8 pulu sayar; pulları yayıp aralarını açtığınızda \"şimdi kaç?\" diye sorulduğunda yeniden saymadan \"yine sekiz\" der. Dizilim, aralık ya da düzen değişse de çokluğun değişmediğini bilir.",
    teacher: "Sayı korunumu, miktarın görünüşten bağımsız olduğunu kavramaktır (Piaget'nin klasik korunum görevi): nesneler yayılınca \"daha çok\", toplanınca \"daha az\" sanan çocuk henüz korunumu kuramamıştır. Saymadan \"aynı\" diyebilmesi asıl kazanımdır; birebir eşleme yapıp \"hiçbiri eklenmedi/çıkmadı\" mantığını dile döktürün. Bu, sağlam sayı kavramının ve toplama-çıkarmada miktarın izlenmesinin göstergesidir.",
    act: {
      materials: ["DokunSay pulları (iki özdeş 8'lik sıra)", "yayma/toplama için düz bir zemin"],
      steps: [
        "İki sırayı birebir karşılıklı dizin; çocuk \"eşit mi?\" desin (evet, ikisi de 8).",
        "Bir sırayı gözünün önünde yayıp aralıkları açın: \"şimdi hangisinde daha çok?\".",
        "\"Sayalım mı?\" demeden \"hiç ekledim mi, çıkardım mı?\" diye düşündürün.",
        "Çocuk \"yine eşit/aynı\" derse mantığını (\"sadece açtın\") söyletin.",
      ],
      criterion: "Dizilim değiştirildiğinde, yeniden saymadan çokluğun korunduğunu (\"yine aynı\") söyler ve gerekçelendirirse ✓",
      easy: "Küçük kümeyle (5) ve az yaymayla başlayın; birebir eşlemeyi gösterin.",
      hard: "Daha büyük kümeler (12) ve hem yayma hem üst üste yığma ile yoklayın.",
    },
    viz: { t: "tenframe", n: 8, frames: 1 },
    tool: "bar",
  },
  { // 18 — İleri-Geri Sayan (Onlar ve Birler) (114–126 ay)
    how: "Çocuk 47'den \"on ileri\" → 57, \"bir geri\" → 56 gibi onluk ve birlik adımlarla esnekçe gidip gelir; \"elli yediden üç onluk geri\" deyince doğrudan 27'ye iner. Onlar ve birler basamağında bağımsız ve esnek hareket eder.",
    teacher: "Bu en üst sayma düzeyidir: çocuk sayı doğrusunda onluk ve birlik sıçramalarla iki yönde esnek gezinir — bu, zihinden çok basamaklı toplama-çıkarmanın (47+30, 56−9) doğrudan temelidir. Onluk atlarken birler basamağının değişmediğini fark etmesi kritiktir (47→57: birler hep 7). DokunSay Basamak bloklarıyla onluk ekleyip çıkararak bu sıçramaları somutlaştırın; \"hangi basamak değişti?\" diye sürekli sorgulayın.",
    act: {
      materials: ["DokunSay Basamak blokları (onluk çubuk + birlik küp)", "yüz tablosu (1–100)", "2 basamaklı sayı kartları"],
      steps: [
        "47'yi bloklarla kurun: \"On ileri\" deyin, bir onluk çubuk ekletip 57 dedirtin.",
        "\"Hangi basamak değişti?\" diye sordurun (onlar; birler hep 7).",
        "Yüz tablosunda 47'den bir satır aşağı (=+10), bir kutu sola (=−1) attırın.",
        "\"Elli altıdan iki onluk ve bir birlik geri\" gibi karışık adımlar verin.",
      ],
      criterion: "İki basamaklı bir sayıdan onluk/birlik adımlarla ileri-geri esnek sayar ve hangi basamağın değiştiğini söylerse ✓",
      easy: "Yalnız onluk adımlarla (+10/−10) ve yüz tablosu desteğiyle çalışın.",
      hard: "Onluk geçiş içeren adımlar (48'den 5 ileri) ve yalnızca zihinden (blok/tablo olmadan).",
    },
    viz: { t: "baseten", tens: 4, ones: 7 },
    tool: "basamak",
  },
]
