/**
 * DokunSay Platform — Araç Kataloğu
 *
 * Platform menüsünde görüntülenecek her aracın meta verisi.
 * Kurmancî terminoloji FerMat sözlüğüne göre hizalıdır
 * (bkz. _platform/shared/FERMAT.ku.md).
 * AR/FA eğitim terminolojisi (standart akademik) kullanılır.
 */

export const TOOLS = [
  {
    id: 'bar',
    name: {
      tr: 'DokunSay Bar',
      ku: 'DokunSay Bar',
      en: 'DokunSay Bar',
      ar: 'دكن‑ساي القضبان',
      fa: 'دکن‑سای میله‌ها',
    },
    subtitle: {
      tr: 'Çubuklar ve Pullar',
      ku: 'Çovik û Pul',
      en: 'Rods & Chips',
      ar: 'القضبان والرقاقات',
      fa: 'میله‌ها و ژتون‌ها',
    },
    description: {
      tr: 'Manipülatif çubuk ve renkli pullarla sayma, değer ve dört işlem.',
      ku: 'Hejmartin, nirx û çar kirarî — bi çovik û pulên rengîn.',
      en: 'Counting, value and four operations with manipulative rods and colored chips.',
      ar: 'العدّ والقيمة والعمليات الأربع بقضبان ورقاقات ملوّنة.',
      fa: 'شمارش، ارزش و چهار عمل با میله‌های دست‌ورزی و ژتون‌های رنگی.',
    },
    icon: '🧮',
    color: '#f59e0b',
    ageRange: '5-10',
    topics: {
      tr: ['Sayma', 'Toplama', 'Çıkarma', 'Parça-Bütün'],
      ku: ['Hejmartin', 'Zêdekirin', 'Kemkirin', 'Par û Gişt'],
      en: ['Counting', 'Addition', 'Subtraction', 'Part-Whole'],
      ar: ['العدّ', 'الجمع', 'الطرح', 'الجزء والكلّ'],
      fa: ['شمارش', 'جمع', 'تفریق', 'جزء و کل'],
    },
    framework: 'CRA + Bruner',
    devUrl: 'http://localhost:3001',
    prodPath: '/DokunSayBar/',
    folder: 'DokunSayBar',
    status: 'stable',
  },
  {
    id: 'basamak',
    name: {
      tr: 'DokunSay Basamak',
      ku: 'DokunSay Nirxane',
      en: 'DokunSay Place Value',
      ar: 'دكن‑ساي المنازل',
      fa: 'دکن‑سای ارزش مکانی',
    },
    subtitle: {
      tr: 'Basamak Değeri',
      ku: 'Nirxê Pêşekê',
      en: 'Place Value',
      ar: 'القيمة المنزلية',
      fa: 'ارزش مکانی',
    },
    description: {
      tr: 'Birlik-onluk-yüzlük-binlik bloklarıyla ondalık sayı sistemi öğretimi.',
      ku: 'Pergala dehane — bi blokên yekan, dehan, sedan û hezaran.',
      en: 'Teaching the decimal system with ones/tens/hundreds/thousands blocks.',
      ar: 'تعليم النظام العشري بقطع الآحاد والعشرات والمئات والآلاف.',
      fa: 'آموزش دستگاه دهدهی با بلوک‌های یکان، دهگان، صدگان و هزارگان.',
    },
    icon: '🔢',
    color: '#3b82f6',
    ageRange: '6-10',
    topics: {
      tr: ['Basamak Değeri', 'Gruplama', 'Bölme', 'Yer Değeri'],
      ku: ['Nirxê Pêşekê', 'Komkirin', 'Veqetandin', 'Cih û Nirx'],
      en: ['Place Value', 'Grouping', 'Decomposition', 'Positional System'],
      ar: ['القيمة المنزلية', 'التجميع', 'التفكيك', 'النظام الوضعي'],
      fa: ['ارزش مکانی', 'گروه‌بندی', 'تجزیه', 'دستگاه ارزشی'],
    },
    framework: 'Bloom L1-L5 + Dienes',
    devUrl: 'http://localhost:3002',
    prodPath: '/DokunSayBasamak/',
    folder: 'DokunSayBasamak',
    status: 'stable',
  },
  {
    id: 'clock',
    name: {
      tr: 'DokunSay Clock',
      ku: 'DokunSay Saet',
      en: 'DokunSay Clock',
      ar: 'دكن‑ساي الساعة',
      fa: 'دکن‑سای ساعت',
    },
    subtitle: {
      tr: 'Saat ve Zaman',
      ku: 'Saet û Dem',
      en: 'Time & Clock',
      ar: 'الساعة والزمن',
      fa: 'ساعت و زمان',
    },
    description: {
      tr: 'Analog ve dijital saatle zaman okuma, kavram inşası.',
      ku: 'Xwendina demê û avakirina têgeha demê — bi saetên analog û dîjîtal.',
      en: 'Time reading and concept building with analog & digital clocks.',
      ar: 'قراءة الوقت وبناء المفهوم بالساعة التماثلية والرقمية.',
      fa: 'خواندن زمان و ساخت مفهوم با ساعت عقربه‌ای و دیجیتال.',
    },
    icon: '🕐',
    color: '#22c55e',
    ageRange: '6-9',
    topics: {
      tr: ['Saat Okuma', 'Dakika', 'Yarım/Çeyrek', 'Dijital-Analog'],
      ku: ['Xwendina Demê', 'Deqe', 'Nîv/Çarek', 'Dîjîtal-Analog'],
      en: ['Time Reading', 'Minute', 'Half/Quarter', 'Digital-Analog'],
      ar: ['قراءة الساعة', 'الدقيقة', 'النصف/الربع', 'رقمي-تماثلي'],
      fa: ['خواندن ساعت', 'دقیقه', 'نیم/ربع', 'دیجیتال-عقربه‌ای'],
    },
    framework: 'Piaget + CRA',
    devUrl: 'http://localhost:3003',
    prodPath: '/DokunSayClock/',
    folder: 'DokunSayClock',
    status: 'stable',
  },
  {
    id: 'kesir',
    name: {
      tr: 'DokunSay Kesir',
      ku: 'DokunSay Parjimar',
      en: 'DokunSay Fraction',
      ar: 'دكن‑ساي الكسور',
      fa: 'دکن‑سای کسر',
    },
    subtitle: {
      tr: 'Kesirler',
      ku: 'Parjimar',
      en: 'Fractions',
      ar: 'الكسور',
      fa: 'کسرها',
    },
    description: {
      tr: 'Bar modeli, pasta grafik ve sayı doğrusuyla kesir öğretimi.',
      ku: 'Parjimar — bi modela çovik, bi nexşeya gilover û bi jimarxêzê.',
      en: 'Fractions via bar model, pie chart and number line.',
      ar: 'تعليم الكسور بنموذج القِطع ومخطّط الدائرة وخط الأعداد.',
      fa: 'آموزش کسر با مدل میله، نمودار دایره‌ای و خط اعداد.',
    },
    icon: '🍕',
    color: '#ef4444',
    ageRange: '6-10',
    topics: {
      tr: ['Bütün-Parça', 'Birim Kesir', 'Denklik', 'Dört İşlem'],
      ku: ['Gişt û Par', 'Parjimara Yekane', 'Hevkêşî', 'Çar Kirarî'],
      en: ['Whole-Part', 'Unit Fraction', 'Equivalence', 'Four Operations'],
      ar: ['الكلّ والجزء', 'كسر الوحدة', 'التكافؤ', 'العمليات الأربع'],
      fa: ['کل و جزء', 'کسر واحد', 'هم‌ارزی', 'چهار عمل'],
    },
    framework: 'CRA + MEB Müfredatı',
    devUrl: 'http://localhost:3004',
    prodPath: '/DokunSayFraction/',
    folder: 'DokunSayKesir',
    status: 'stable',
  },
  {
    id: 'tam',
    name: {
      tr: 'DokunSay Tam',
      ku: 'DokunSay Tam',
      en: 'DokunSay Integer',
      ar: 'دكن‑ساي الأعداد الصحيحة',
      fa: 'دکن‑سای اعداد صحیح',
    },
    subtitle: {
      tr: 'Tam Sayılar',
      ku: 'Hejmarên Tam',
      en: 'Integers',
      ar: 'الأعداد الصحيحة',
      fa: 'اعداد صحیح',
    },
    description: {
      tr: 'Pozitif/negatif pullar, sıfır çifti ve senaryolarla tam sayı işlemleri.',
      ku: 'Kirarîyên hejmarên tam — bi pulên erênî û neyînî, bi cotên sifirê û bi senaryoyan.',
      en: 'Integer operations with positive/negative chips, zero pairs and scenarios.',
      ar: 'عمليات الأعداد الصحيحة بالرقاقات الموجبة والسالبة وأزواج الصفر والسيناريوهات.',
      fa: 'عملیات اعداد صحیح با ژتون‌های مثبت و منفی، جفت‌های صفر و سناریوها.',
    },
    icon: '➕➖',
    color: '#8b5cf6',
    ageRange: '10-13',
    topics: {
      tr: ['Negatif Sayı', 'Sıfır Çifti', 'Termometre', 'Asansör'],
      ku: ['Hejmara Neyînî', 'Cotê Sifir', 'Pîvana Germahîyê', 'Asansor'],
      en: ['Negative Number', 'Zero Pair', 'Thermometer', 'Elevator'],
      ar: ['العدد السالب', 'زوج الصفر', 'ميزان الحرارة', 'المصعد'],
      fa: ['عدد منفی', 'جفت صفر', 'دماسنج', 'آسانسور'],
    },
    framework: 'Sıfır Çifti Modeli + Senaryo',
    devUrl: 'http://localhost:3005',
    prodPath: '/DokunSayExact/',
    folder: 'DokunSayTam',
    status: 'stable',
  },
  {
    id: 'geo',
    name: {
      tr: 'DokunSay Geo',
      ku: 'DokunSay Geo',
      en: 'DokunSay Geo',
      ar: 'دكن‑ساي الهندسة',
      fa: 'دکن‑سای هندسه',
    },
    subtitle: {
      tr: 'Geometri',
      ku: 'Cîyometrî',
      en: 'Geometry',
      ar: 'الهندسة',
      fa: 'هندسه',
    },
    description: {
      tr: 'Van Hiele 5-faz modeliyle 2B/3B şekiller, ölçüm ve ispat.',
      ku: 'Bi modela Van Hiele ya pênc qonax — teşeyên 2D û 3D, pîvandin û îspat.',
      en: '2D/3D shapes, measurement and proof via Van Hiele 5-phase model.',
      ar: 'أشكال ثنائية وثلاثية الأبعاد، قياس وبرهان عبر نموذج Van Hiele الخماسي.',
      fa: 'شکل‌های ۲بعدی و ۳بعدی، اندازه‌گیری و اثبات با مدل پنج‌مرحله‌ای Van Hiele.',
    },
    icon: '🔺',
    color: '#14b8a6',
    ageRange: '5-14',
    topics: {
      tr: ['Şekiller', 'Geoboard', 'Tangram', 'Hiyerarşi'],
      ku: ['Teşe', 'Geoboard', 'Tangram', 'Hîyerarşî'],
      en: ['Shapes', 'Geoboard', 'Tangram', 'Hierarchy'],
      ar: ['الأشكال', 'لوحة الهندسة', 'تانغرام', 'تسلسل هرمي'],
      fa: ['شکل‌ها', 'تختۀ هندسی', 'تانگرام', 'سلسله‌مراتب'],
    },
    framework: 'Van Hiele + Crowley',
    devUrl: 'http://localhost:3006',
    prodPath: '/dokunsay-geo/',
    folder: 'Dokunsay-geo',
    status: 'stable',
  },
  {
    id: 'veri',
    name: {
      tr: 'DokunSay Veri',
      ku: 'DokunSay Dane',
      en: 'DokunSay Data',
      ar: 'دكن‑ساي البيانات',
      fa: 'دکن‑سای داده',
    },
    subtitle: {
      tr: 'Veri ve İstatistik',
      ku: 'Dane û Amarî',
      en: 'Data & Statistics',
      ar: 'البيانات والإحصاء',
      fa: 'داده و آمار',
    },
    description: {
      tr: 'Curcio seviyeleri ve GAISE ile grafik okuma, istatistiksel okuryazarlık.',
      ku: 'Xwendina nexşeyan û xwendewariya amarî — bi astên Curcio û çarçoveya GAISE.',
      en: 'Graph reading and statistical literacy with Curcio levels and GAISE.',
      ar: 'قراءة الرسوم والقراءة الإحصائية عبر مستويات Curcio وإطار GAISE.',
      fa: 'خواندن نمودار و سواد آماری با سطوح Curcio و چارچوب GAISE.',
    },
    icon: '📊',
    color: '#ec4899',
    ageRange: '7-15',
    topics: {
      tr: ['Grafik Okuma', 'Yanıltma', 'Ortalama', 'Olasılık'],
      ku: ['Xwendina Nexşeyan', 'Xapandin', 'Navgîn', 'Îhtîmal'],
      en: ['Graph Reading', 'Deception', 'Average', 'Probability'],
      ar: ['قراءة الرسوم', 'التضليل', 'المتوسّط', 'الاحتمال'],
      fa: ['خواندن نمودار', 'فریب', 'میانگین', 'احتمال'],
    },
    framework: 'Curcio + GAISE + PPDAC',
    devUrl: 'http://localhost:3007',
    prodPath: '/dokunsay-veri/',
    folder: 'Dokunsay-veri-app',
    status: 'stable',
  },
];

export const TOOL_CATEGORIES = {
  tr: [
    { id: 'number', label: 'Sayı & İşlem', tools: ['bar', 'basamak', 'tam', 'kesir'] },
    { id: 'measure', label: 'Ölçme', tools: ['clock'] },
    { id: 'geometry', label: 'Geometri', tools: ['geo'] },
    { id: 'data', label: 'Veri', tools: ['veri'] },
  ],
  ku: [
    { id: 'number', label: 'Hejmar û Kirarî', tools: ['bar', 'basamak', 'tam', 'kesir'] },
    { id: 'measure', label: 'Pîvandin', tools: ['clock'] },
    { id: 'geometry', label: 'Cîyometrî', tools: ['geo'] },
    { id: 'data', label: 'Dane', tools: ['veri'] },
  ],
  en: [
    { id: 'number', label: 'Number & Operation', tools: ['bar', 'basamak', 'tam', 'kesir'] },
    { id: 'measure', label: 'Measurement', tools: ['clock'] },
    { id: 'geometry', label: 'Geometry', tools: ['geo'] },
    { id: 'data', label: 'Data', tools: ['veri'] },
  ],
  ar: [
    { id: 'number', label: 'العدد والعملية', tools: ['bar', 'basamak', 'tam', 'kesir'] },
    { id: 'measure', label: 'القياس', tools: ['clock'] },
    { id: 'geometry', label: 'الهندسة', tools: ['geo'] },
    { id: 'data', label: 'البيانات', tools: ['veri'] },
  ],
  fa: [
    { id: 'number', label: 'عدد و عملیات', tools: ['bar', 'basamak', 'tam', 'kesir'] },
    { id: 'measure', label: 'اندازه‌گیری', tools: ['clock'] },
    { id: 'geometry', label: 'هندسه', tools: ['geo'] },
    { id: 'data', label: 'داده', tools: ['veri'] },
  ],
};
