export const ACTIVITIES = [
  { n: "Serbest Keşif",          i: "🎨", cat: "keşif",       diff: 1, d: "Blokları kanvasa sürükleyerek basamak değerini keşfet!",                            s: {} },
  { n: "Birlikler",              i: "🟡", cat: "kavram",      diff: 1, d: "Birlik küplerini sürükle. Her küp 1 değerinde. 7 küp = 7",                           s: { ones: 7, cols: 2 } },
  { n: "Onluklar",               i: "🟠", cat: "kavram",      diff: 1, d: "Onluk çubuğu sürükle. Her çubuk 10 birlik içerir. 3 çubuk = 30",                    s: { tens: 3, cols: 2 } },
  { n: "Yüzlükler",              i: "🔵", cat: "kavram",      diff: 1, d: "Yüzlük kareyi sürükle. Her kare 100 birlik = 10 onluk içerir.",                      s: { huns: 1, cols: 3 } },
  { n: "10 Birlik = 1 Onluk",    i: "🔄", cat: "kavram",      diff: 2, d: "10 birlik küpü ekledik. Birine tıkla → 🔗 Grupla! (G tuşu)",                         s: { ones: 10, cols: 2 } },
  { n: "Sayı Oluştur: 34",       i: "🔢", cat: "işlem",       diff: 1, d: "3 onluk + 4 birlik = 34",                                                            s: { tens: 3, ones: 4, cols: 2 } },
  { n: "Sayı Oluştur: 152",      i: "🔢", cat: "işlem",       diff: 2, d: "1 yüzlük + 5 onluk + 2 birlik = 152",                                               s: { huns: 1, tens: 5, ones: 2, cols: 3 } },
  { n: "Sayı Oluştur: 2047",     i: "🔢", cat: "işlem",       diff: 3, d: "2 binlik + 0 yüzlük + 4 onluk + 7 birlik = 2047",                                   s: { ths: 2, tens: 4, ones: 7, cols: 4 } },
  { n: "Toplama: 25+18",         i: "➕", cat: "işlem",       diff: 2, d: "25 ve 18 bloklarla gösterildi. Birlikler: 5+8=13 → 10 birliğe tıkla → Grupla!",     s: { tens: 3, ones: 13, cols: 2 } },
  { n: "Çıkarma: 43−17",         i: "➖", cat: "işlem",       diff: 3, d: "43 gösterildi. 7 birlik çıkarmak için 1 onluğa tıkla → ✂ Çöz!",                     s: { tens: 4, ones: 3, cols: 2 } },
  { n: "Karşılaştır",            i: "⚖️", cat: "karşılaştır", diff: 2, d: "Soldaki 256, sağdaki 289. Yüzlükler eşit — onluklara bak!",                     s: { huns: 2, tens: 5, ones: 6, cols: 3, decomp: true } },
  { n: "Y1: 3, 30 ve 300",       i: "🔍", cat: "yanılgı",     diff: 2, d: "324 gösterildi. 3 yüzlük = 300! Basamak değeri ≠ rakam.",                           s: { huns: 3, tens: 2, ones: 4, cols: 3, decomp: true } },
  { n: "Y2: Sıfırın önemi",      i: "🔍", cat: "yanılgı",     diff: 2, d: "304 gösterildi. Onluklar basamağı 0 — sıfır yer tutucu!",                           s: { huns: 3, ones: 4, cols: 3, decomp: true } },
  { n: "Y3: Gruplama hatası",    i: "🔍", cat: "yanılgı",     diff: 3, d: "2 yüzlük + 13 onluk + 1 birlik ekledik. 13 onluğa tıkla → Grupla!",                 s: { huns: 2, tens: 13, ones: 1, cols: 3 } },
  { n: "Y4: Sözel→Sembolik",     i: "🔍", cat: "yanılgı",     diff: 2, d: "304 gösterildi. 'Üç yüz dört' — 3004 değil!",                                       s: { huns: 3, ones: 4, cols: 3, decomp: true } },
  { n: "Y5: Büyük rakam=Büyük?", i: "🔬", cat: "yanılgı",     diff: 2, d: "89 ve 102 karşılaştır. Basamak sayısı önemli!",                                      s: { huns: 1, ones: 2, cols: 3, decomp: true } },
  { n: "Market Alışverişi",      i: "🛒", cat: "senaryo",     diff: 1, d: "45₺ + 27₺ → toplam bloklar ekledik. Grupla!",                                       s: { tens: 6, ones: 12, cols: 2 } },
  { n: "Uzunluk Ölçme",          i: "📏", cat: "senaryo",     diff: 2, d: "135cm gösterildi: 1 yüzlük + 3 onluk + 5 birlik",                                   s: { huns: 1, tens: 3, ones: 5, cols: 3 } },
  { n: "Sınıf Mevcudu",          i: "🏫", cat: "senaryo",     diff: 1, d: "386 öğrenci gösterildi.",                                                            s: { huns: 3, tens: 8, ones: 6, cols: 3 } },
  { n: "Para Bozma",             i: "💰", cat: "senaryo",     diff: 2, d: "500₺ gösterildi. Yüzlüğe tıkla → ✂ Çöz!",                                           s: { huns: 5, cols: 3 } },
];
