// Klasik hızlı etkinlikler — seviye başına 7 quick-quiz.
// Klasik hızlı etkinlikler (eski VH_ACTS):
export const VH_ACTS_OLD=[
  // L0 — Görsel (7)
  {id:"l0_a",level:0,cra:"C",icon:"👁",
   label:{tr:"Üçgeni Bul",ku:"Sêgoşeyê Bibîne",en:"Find the Triangle"},
   q:{tr:"Aşağıdakilerden hangisi üçgendir?",ku:"Ji van kîjan sêgoşe ye?",en:"Which of these is a triangle?"},
   opts:["eq_tri","square","circle","hexagon"],correct:"eq_tri",
   hint:{tr:"3 düz kenarı olan şekle üçgen denir.",ku:"Teşeya bi 3 kêlekên rast sêgoşe ye.",en:"A triangle has exactly 3 straight sides."}},
  {id:"l0_b",phase:"DO",level:0,icon:"🔀",
   label:{tr:"Dörtgen Bul",ku:"Çarhêlan Bibîne",en:"Find Quadrilaterals"},
   q:{tr:"Hangileri dörtgendir? (Birden fazla seçilebilir)",ku:"Kîjan çarhêl in? (Zêdetir jî tê hilbijartin)",en:"Which are quadrilaterals? (Select all that apply)"},
   opts:["square","rectangle","trapezoid","eq_tri","circle"],correct:["square","rectangle","trapezoid"],multi:true,
   hint:{tr:"Dörtgenlerin tam 4 kenarı vardır.",ku:"Çarhêl 4 kêlekên xwe hene.",en:"Quadrilaterals have exactly 4 sides."}},
  {id:"l0_c",phase:"I",level:0,icon:"🌍",
   label:{tr:"Gerçek Yaşam",ku:"Jiyana Rastîn",en:"Real Life"},
   q:{tr:"Stop tabelasının şekli nedir?",ku:"Teşeya levha STOP çi ye?",en:"What shape is a stop sign?"},
   opts:["octagon","circle","square","hexagon"],correct:"octagon",
   hint:{tr:"Stop tabelası 8 kenarlı düzgün sekizgendir.",ku:"Levha STOP heşthêla rêkpêk e.",en:"A stop sign is a regular octagon with 8 sides."}},
  {id:"l0_d",phase:"DO",level:0,icon:"🔢",
   label:{tr:"Kenar Say",ku:"Kêlekan Bijimêre",en:"Count Sides"},
   q:{tr:"Karenin kaç kenarı vardır?",ku:"Çaryalî çend kêlek hene?",en:"How many sides does a square have?"},
   answer:4,min:0,max:10,
   hint:{tr:"Kareyi parmağınla çevre boyunca iz et.",ku:"Çaryaliyê bi tiliya xwe dişopîne.",en:"Trace around the square with your finger."}},
  {id:"l0_e",phase:"E",level:0,icon:"◯",
   label:{tr:"Daire mi Çember mi?",ku:"Dayre an Xelek?",en:"Disk or Circle?"},
   q:{tr:"Yalnızca sınır çizgisi olan, içi boş olan şekil hangisidir?",ku:"Ya ku tenê xêza sînorê wê heye û hundurê wê vala ye kîjan e?",en:"Which shape has only a boundary line with no interior?"},
   opts:["circle","disk","square","eq_tri"],correct:"circle",
   hint:{tr:"Çember yalnızca eğri çizgidir — alanı yoktur, yalnız uzunluğu (çevresi) vardır. Daire ise çemberin sınırladığı iç bölge ile birlikte bütünün kendisidir; alanı vardır.",ku:"Xelek tenê xêzeke xwar e — rûberê wê tune, tenê dirêjahiya wê heye. Dayre jî herêma hundur bi xelekê re tevahî ye; rûberê wê heye.",en:"A circle is just the curved boundary line — it has no area, only length (circumference). A disk is the circle together with the interior region it bounds; it has area."}},
  {id:"l0_f",phase:"FO",level:0,icon:"🍕",
   label:{tr:"Dilim Sayısı",ku:"Reqema Parçeyê",en:"Slice Count"},
   q:{tr:"Düzgün altıgen kaç eşit parçaya bölünebilir?",ku:"Şeşhêla rêkpêk dikare bibe çend parçeyên wekhev?",en:"How many equal parts can a regular hexagon be divided into?"},
   answer:6,min:1,max:12,
   hint:{tr:"Merkeze çizilen her çizgi bir parça oluşturur. 6 kenar = 6 parça.",ku:"Her xêza navendê yek parçe çêdike. 6 kêlek = 6 parçe.",en:"Each line to center makes one slice. 6 sides = 6 slices."}},
  {id:"l0_g",phase:"FO",level:0,icon:"👀",
   label:{tr:"Köşe Say",ku:"Goşeyan Bijimêre",en:"Count Corners"},
   q:{tr:"Beşgenin kaç köşesi vardır?",ku:"Pênchêlê çend goşe hene?",en:"How many corners does a pentagon have?"},
   answer:5,min:0,max:10,
   hint:{tr:"Her kenar biri bir köşe ile biter; kenar sayısı = köşe sayısı.",ku:"Her kêlek bi goşeyek bidawî dibe; hejmara kêlekan = hejmara goşeyan.",en:"Each side ends at a corner; sides = corners."}},

  // L1 — Analiz (7)
  {id:"l1_a",phase:"DO",level:1,icon:"📐",
   label:{tr:"Dik Açı Say",ku:"Guçên Rastan Bijimêre",en:"Count Right Angles"},
   q:{tr:"Dikdörtgende kaç dik açı vardır?",ku:"Di çarhêla rastê de çend guçên rast hene?",en:"How many right angles does a rectangle have?"},
   answer:4,min:0,max:8,
   hint:{tr:"Dik açı 90°'dir; her köşede bir tane.",ku:"Guça rast 90° ye; li her goşeyê yek heye.",en:"A right angle is 90°; there's one at each corner."}},
  {id:"l1_b",phase:"DO",level:1,icon:"∥",
   label:{tr:"Paralel Kenar",ku:"Kêlekên Hevyalî",en:"Parallel Sides"},
   q:{tr:"Hangi dörtgenlerde karşılıklı kenarlar paralel? (Tümünü seç)",ku:"Di kîjan çarhêlan de kêlekên rûbirû hevyalî ne? (Hemûyan hilbijêre)",en:"Which quadrilaterals have parallel opposite sides? (Select all)"},
   opts:["square","rectangle","trapezoid","rhombus","parallelogram","kite"],correct:["square","rectangle","rhombus","parallelogram"],multi:true,
   hint:{tr:"Paralel kenarlar hiç kesişmez; yamukta yalnız 1 çift, uçurtmada 0 çift vardır.",ku:"Kêlekên hevyalî qet nakesên; di trapezoîdê de 1 cot, di çargoşeya balafirê de 0 cot.",en:"Parallel sides never meet; trapezoid has 1 pair, kite has 0."}},
  {id:"l1_c",phase:"E",level:1,icon:"∠",
   label:{tr:"Açı Türü",ku:"Cureyê Guçê",en:"Angle Type"},
   q:{tr:"Eşkenar üçgendeki her açı kaç derecedir?",ku:"Her guça di sêgoşeya wekhev de çend derece ye?",en:"How many degrees is each angle in an equilateral triangle?"},
   answer:60,min:0,max:180,
   hint:{tr:"Üçgende iç açılar toplamı 180°; 3 eşit açı = 180÷3 = 60°.",ku:"Di sêgoşeyê de komê guçên hundur 180° ye; 3 guçên wekhev = 60°.",en:"Triangle interior angles sum to 180°; 3 equal angles = 60°."}},
  {id:"l1_d",phase:"DO",level:1,icon:"⟺",
   label:{tr:"Simetri Ekseni",ku:"Eksena Nîvheviyê",en:"Lines of Symmetry"},
   q:{tr:"Karenin kaç simetri ekseni vardır?",ku:"Çaryaliyê çend eksena nîvheviyê hene?",en:"How many lines of symmetry does a square have?"},
   answer:4,min:0,max:8,
   hint:{tr:"Yatay + dikey + 2 köşegen ekseni = toplam 4.",ku:"Asoyî + tîkkî + 2 eksena goşeyê = 4 bi tevahî.",en:"Horizontal + vertical + 2 diagonal axes = 4 total."}},
  {id:"l1_e",phase:"E",level:1,icon:"📏",
   label:{tr:"Düzgün mü?",ku:"Rêkpêk e?",en:"Is it Regular?"},
   q:{tr:"Hangi şekil hem eşit kenarlı hem eşit açılıdır?",ku:"Kîjan teşe hem kêlekên wekhev hem guçên wekhev hene?",en:"Which shape has both equal sides and equal angles?"},
   opts:["rectangle","rhombus","square","trapezoid"],correct:"square",
   hint:{tr:"Düzgün çokgen: tüm kenarlar ve açılar eşit. Dikdörtgende açılar eşit ama kenarlar değil; eşkenar dörtgende kenarlar eşit ama açılar değil.",ku:"Çendhêla rêkpêk: hemû kêlek û guç wekhev. Di çarhêla rastê de guç wekhev lê kêlek ne; di lozengê de kêlek wekhev lê guç ne.",en:"Regular polygon: all sides and angles equal. Rectangle has equal angles but not sides; rhombus has equal sides but not angles."}},
  {id:"l1_f",phase:"FO",level:1,icon:"🔺",
   label:{tr:"Açı Toplamı",ku:"Komê Guçan",en:"Angle Sum"},
   q:{tr:"Dörtgenin iç açıları toplamı kaç derecedir?",ku:"Komê guçên hundurê çarhêlê çend derece ye?",en:"What is the sum of interior angles in a quadrilateral?"},
   answer:360,min:0,max:720,
   hint:{tr:"Her dörtgen 2 üçgene bölünebilir: 2 × 180° = 360°.",ku:"Her çarhêl dikare bibe 2 sêgoşe: 2 × 180° = 360°.",en:"Any quadrilateral splits into 2 triangles: 2 × 180° = 360°."}},
  {id:"l1_g",phase:"FO",level:1,icon:"🔵",
   label:{tr:"Çemberde Açı",ku:"Guça di Xelekê",en:"Circle Angle"},
   q:{tr:"Bir çemberde kaç derece vardır?",ku:"Di xelekekê de çend derece hene?",en:"How many degrees are in a full circle?"},
   answer:360,min:0,max:720,
   hint:{tr:"Tam bir dönüş = 360°. Bu bütün açı sisteminin temelidir.",ku:"Zivirandineke tam = 360°. Ev bingeha hemû pergala guçan e.",en:"A full rotation = 360°. This is the basis of all angle systems."}},

  // L2 — Soyutlama (7)
  {id:"l2_a",phase:"E",level:2,icon:"⊂",
   label:{tr:"Kare ⊂ Dikdörtgen",ku:"Çaryalî ⊂ Çarhêla Rast",en:"Square ⊂ Rectangle"},
   q:{tr:"Kare aynı zamanda bir dikdörtgen midir?",ku:"Çaryalî di heman demê de çarhêla rast e?",en:"Is a square also a rectangle?"},
   opts:{tr:["Evet — 4 dik açısı var","Hayır — sadece kare","Bazen","Hiçbir zaman"],
         ku:["Erê — 4 guçên rastan hene","Na — tenê çaryalî ye","Carinan","Tu caran"],
         en:["Yes — it has 4 right angles","No — only a square","Sometimes","Never"]},
   correct:0,
   hint:{tr:"Dikdörtgen tanımı: 4 dik açılı dörtgen. Kare bu koşulu tam sağlar.",ku:"Defînisyona çarhêla rast: çarhêlek bi 4 guçên rast. Çaryalî vê şertê temam pêk tîne.",en:"Rectangle definition: quadrilateral with 4 right angles. A square fully satisfies this."}},
  {id:"l2_b",phase:"E",level:2,icon:"∀",
   label:{tr:"Her Zaman",ku:"Her Tim",en:"Always True"},
   q:{tr:"Tüm paralelkenarlarda her zaman doğru olan hangisi?",ku:"Di hemû paralelograman de her tim rast e kîjan?",en:"Which is always true for all parallelograms?"},
   opts:{tr:["Tüm açılar eşittir","Tüm kenarlar eşittir","Karşılıklı açılar eşittir","Bir açı 90°'dir"],
         ku:["Hemû guç wekhev in","Hemû kêlek wekhev in","Guçên rûbirû wekhev in","Yek guç 90° ye"],
         en:["All angles are equal","All sides are equal","Opposite angles are equal","One angle is 90°"]},
   correct:2,
   hint:{tr:"Paralelkenarda: karşılıklı açılar eşit ve karşılıklı kenarlar eşit. Açıların 90° olması zorunlu değil.",ku:"Di paralelograma de: guçên rûbirû wekhev û kêlekên rûbirû wekhev. Guç ne hewce ye 90° be.",en:"In parallelograms: opposite angles are equal and opposite sides are equal. Angles need not be 90°."}},
  {id:"l2_c",phase:"IN",level:2,icon:"🗂",
   label:{tr:"Hiyerarşi",ku:"Hîyerarşî",en:"Hierarchy"},
   q:{tr:"'Her kare eşkenar dörtgendir' cümlesi doğru mudur?",ku:"'Her çaryalî lozeng e' hevoka rast e?",en:"Is 'every square is a rhombus' true?"},
   opts:{tr:["Evet — her kare eşit kenarlıdır","Hayır — farklı şekillerdir","Bazen doğrudur","Yalnız 90° açı ile"],
         ku:["Erê — her çaryalî kêlekên wekhev hene","Na — teşeyên cûda ne","Carinan rast e","Tenê bi guça 90°"],
         en:["Yes — every square has equal sides","No — they are different shapes","Sometimes","Only with 90° angles"]},
   correct:0,
   hint:{tr:"Eşkenar dörtgen: tüm kenarları eşit dörtgen. Karenin 4 eşit kenarı var → kare ⊂ eşkenar dörtgen.",ku:"Lozeng: çarhêlek bi hemû kêlekên wekhev. Çaryaliyê 4 kêlekên wekhev hene → çaryalî ⊂ lozeng.",en:"Rhombus: quadrilateral with all equal sides. A square has 4 equal sides → square ⊂ rhombus."}},
  {id:"l2_d",phase:"IN",level:2,icon:"🔗",
   label:{tr:"Kesişim",ku:"Hevberdê",en:"Intersection"},
   q:{tr:"Hem dikdörtgen hem eşkenar dörtgen olan şekil nedir?",ku:"Hem çarhêla rast hem lozeng kîjan teşe ye?",en:"What shape is both a rectangle and a rhombus?"},
   opts:{tr:["Paralelkenar","Yamuk","Kare","Beşgen"],
         ku:["Paralelogram","Trapezoîd","Çaryalî","Pênchêl"],
         en:["Parallelogram","Trapezoid","Square","Pentagon"]},
   correct:2,
   hint:{tr:"Dikdörtgen ∩ Eşkenar Dörtgen = Kare. Kare hem 4 dik açılı hem 4 eşit kenarlıdır.",ku:"Çarhêla rast ∩ Lozeng = Çaryalî. Çaryaliyê hem 4 guçên rast hem 4 kêlekên wekhev hene.",en:"Rectangle ∩ Rhombus = Square. A square has both 4 right angles and 4 equal sides."}},
  {id:"l2_e",phase:"IN",level:2,icon:"🧩",
   label:{tr:"Özellik Kalıtımı",ku:"Mîrasa Taybetmendiyê",en:"Property Inheritance"},
   q:{tr:"Yamuk neden paralelkenar değildir?",ku:"Çima trapezoîd paralelogram nîne?",en:"Why is a trapezoid NOT a parallelogram?"},
   opts:{tr:["4 kenarı yok","Yalnız 1 çift paralel kenarı var","Hiç açısı yok","Dik açısı yok"],
         ku:["4 kêlek tune","Tenê 1 cotê kêlekên hevyalî hene","Qet guç tune","Guça rast tune"],
         en:["It has no 4 sides","It has only 1 pair of parallel sides","It has no angles","It has no right angle"]},
   correct:1,
   hint:{tr:"Paralelkenar tanımı: 2 çift paralel kenar. Yamukta yalnız 1 çift var → paralelkenar olamaz.",ku:"Defînisyona paralelograma: 2 cot kêlekên hevyalî. Di trapezoîdê de tenê 1 cot heye → nikare paralelogram be.",en:"Parallelogram definition: 2 pairs of parallel sides. Trapezoid has only 1 pair → cannot be a parallelogram."}},
  {id:"l2_f",phase:"FO",level:2,icon:"📊",
   label:{tr:"Sınıflandırma",ku:"Kategorîkirin",en:"Classification"},
   q:{tr:"En geniş kategoriden en dara: sıralamayı tamamla. Dörtgen → ? → Paralelkenar → ?",ku:"Ji kategoriya herî fireh heta ya herî teng: rêzkirinê temam bike. Çarhêl → ? → Paralelogram → ?",en:"From broadest to narrowest: complete the sequence. Quadrilateral → ? → Parallelogram → ?"},
   opts:{tr:["Kare → Dikdörtgen","Dörtgen → Yamuk","Paralelkenar → Kare","Dikdörtgen → Kare"],
         ku:["Çaryalî → Çarhêla Rast","Çarhêl → Trapezoîd","Paralelogram → Çaryalî","Çarhêla Rast → Çaryalî"],
         en:["Square → Rectangle","Quadrilateral → Trapezoid","Parallelogram → Square","Rectangle → Square"]},
   correct:3,
   hint:{tr:"Dörtgen > Paralelkenar > Dikdörtgen > Kare. Her alt küme üst kümenin özelliklerini taşır + ek özellik ekler.",ku:"Çarhêl > Paralelogram > Çarhêla Rast > Çaryalî. Her jêrkom taybetmendiyên malbatê hildigire + zêde dike.",en:"Quadrilateral > Parallelogram > Rectangle > Square. Each subset inherits parent properties + adds constraints."}},
  {id:"l2_g",phase:"IN",level:2,icon:"🌀",
   label:{tr:"Döngüsel mi?",ku:"Dorê ye?",en:"Circular Reasoning?"},
   q:{tr:"'Tüm kareler kare olduğu için eşittir' ifadesi geçerli bir matematiksel argüman mıdır?",ku:"'Hemû çaryalî ji ber ku çaryalî ne wekhev in' gotina matematîkî ya derbasdar e?",en:"Is 'all squares are equal because they are squares' a valid mathematical argument?"},
   opts:{tr:["Evet, açıkça doğrudur","Hayır, döngüsel akıl yürütmedir","Bazen geçerlidir","Sadece geometride geçerlidir"],
         ku:["Erê, eşkere rast e","Na, ev hizirkirina dorê ye","Carinan derbasdar e","Tenê di hindisiyê de"],
         en:["Yes, it's obviously true","No, it is circular reasoning","Sometimes valid","Only in geometry"]},
   correct:1,
   hint:{tr:"Matematiksel kanıt tanımları ve aksiyomları kullanır; 'öyle olduğu için öyle' döngüsel akıl yürütmedir ve geçersizdir.",ku:"Ispata matematîkî defînisyon û aksiyoman bikar tîne; 'ji ber ku wisa ye' hizirkirina dorê ye û ne derbasdar e.",en:"Mathematical proof uses definitions and axioms; 'because it is so' is circular reasoning and invalid."}},

  // ═══ YENİ L0 ETKİNLİKLERİ ═══
  {id:"l0_h",phase:"DO",level:0,icon:"🔄",
   label:{tr:"Döndürülmüş Kare",ku:"Çaryaliya Zivirandî",en:"Rotated Square"},
   q:{tr:"Aşağıdaki 45° döndürülmüş şekil hala kare midir?",ku:"Teşeya 45° hatiye zivirandin hîn çaryalî ye?",en:"Is this shape rotated 45° still a square?"},
   opts:{tr:["Evet, dönse de kare kare kalır","Hayır, artık eşkenar dörtgendir","Hayır, artık baklavadır","Hayır, artık başka bir şekildir"],
         ku:["Erê, heke biziviriye jî çaryalî ye","Na, niha loze(n)g e","Na, niha baqlawa ye","Na, niha teşeyeke din e"],
         en:["Yes, rotated square is still a square","No, now it's a rhombus","No, now it's a diamond","No, it's a different shape"]},
   correct:0,
   hint:{tr:"Bir şeklin ismi yönüne değil özelliklerine bağlıdır. Dönse bile 4 eşit kenar ve 4 dik açı var → hala kare.",ku:"Navê teşeyê ne bi alîyê xwe, bi taybetmendiyan ve girêdayî ye. Heke biziviriye jî 4 kêlekên wekhev û 4 goşeyên rast hene → hîn çaryalî ye.",en:"A shape's name depends on properties, not orientation. Still has 4 equal sides + 4 right angles → still a square."}},
  {id:"l0_i",level:0,cra:"C",icon:"🎨",
   label:{tr:"Renk ve Şekil",ku:"Reng û Teşe",en:"Color vs Shape"},
   q:{tr:"Büyük kırmızı bir daire ile küçük mavi bir daire... Bunlar aynı şekil mi?",ku:"Dayreyeke sor ya mezin û dayreyeke şîn ya piçûk... Ev teşeya heman in?",en:"A big red circle and a small blue circle... Same shape?"},
   opts:{tr:["Evet, ikisi de daire","Hayır, renkleri farklı","Hayır, boyutları farklı","Hayır, ikisi farklı şekil"],
         ku:["Erê, her du jî dayre ne","Na, rengên wan cuda ne","Na, mezinahiya wan cuda ye","Na, her du jî teşeyên cuda ne"],
         en:["Yes, both are circles","No, different colors","No, different sizes","No, different shapes"]},
   correct:0,
   hint:{tr:"Şekil adı renk ve boyuttan bağımsızdır. Sadece geometrik özellikler önemlidir.",ku:"Navê teşeyê ji reng û mezinahiyê serbixwe ye.",en:"Shape name is independent of color and size. Only geometry matters."}},
  {id:"l0_j",phase:"FO",level:0,icon:"🏠",
   label:{tr:"Ev Şekli",ku:"Teşeya Malê",en:"House Shape"},
   q:{tr:"Basit bir ev çizimi hangi şekillerden oluşur?",ku:"Xêzeke sade ya malê ji kîjan teşeyan pêk tê?",en:"A simple house drawing uses which shapes?"},
   opts:{tr:["Kare + Üçgen","Daire + Kare","Üçgen + Üçgen","Dikdörtgen + Kare"],
         ku:["Çaryalî + Sêgoşe","Dayre + Çaryalî","Sêgoşe + Sêgoşe","Dîkdîortgen + Çaryalî"],
         en:["Square + Triangle","Circle + Square","Triangle + Triangle","Rectangle + Square"]},
   correct:0,
   hint:{tr:"Evin gövdesi kare/dikdörtgen, çatısı üçgendir. Günlük nesneleri geometrik parçalara ayırma önemli bir L0 becerisidir.",ku:"Laşê malê çaryalî, serê wê sêgoşe ye.",en:"House body is square, roof is triangle. Decomposing everyday objects into shapes is a key L0 skill."}},

  // ═══ YENİ L1 ETKİNLİKLERİ ═══
  {id:"l1_h",phase:"DO",level:1,icon:"∥",
   label:{tr:"Paralel Kenar",ku:"Kêleka Paralel",en:"Parallel Sides"},
   q:{tr:"Yamuğun kaç çift paralel kenarı vardır?",ku:"Trapezîdê çend cot kêlekên paralel hene?",en:"How many pairs of parallel sides does a trapezoid have?"},
   answer:1,min:0,max:4,
   hint:{tr:"Yamukta SADECE BİR çift paralel kenar vardır (üst-alt). Diğer iki kenar paralel değil. Bu onu paralelkenardan ayırır.",ku:"Di trapezîdê de TENÊ YEK cot kêlek paralel in (jor-jêr). Du kêlekên din ne paralel in.",en:"Trapezoid has EXACTLY ONE pair of parallel sides (top-bottom). The other two are not parallel."}},
  {id:"l1_i",phase:"E",level:1,icon:"🪞",
   label:{tr:"Simetri Eksenleri",ku:"Eksên Sîmetriyê",en:"Symmetry Axes"},
   q:{tr:"Eşkenar üçgenin kaç simetri ekseni vardır?",ku:"Sêgoşeya wekhev çend eksên sîmetriyê hene?",en:"How many symmetry axes does an equilateral triangle have?"},
   answer:3,min:0,max:6,
   hint:{tr:"Eşkenar üçgenin 3 simetri ekseni vardır — her köşeden karşı kenarın orta noktasına bir eksen.",ku:"Sêgoşeya wekhev 3 eksên sîmetriyê hene — ji her goşeyî ber bi navenda kêleka pêşber.",en:"Equilateral triangle has 3 axes — one from each vertex to midpoint of opposite side."}},
  {id:"l1_j",phase:"FO",level:1,icon:"📏",
   label:{tr:"Karşılaştırma",ku:"Beramberkirin",en:"Comparison"},
   q:{tr:"Aşağıdaki özelliklerden hangisi SADECE kareye aittir, dikdörtgene ait değildir?",ku:"Kîjan taybetmendî TENÊ ya çaryalî ye, ne ya dîkdîortgenê ye?",en:"Which property belongs ONLY to squares, NOT rectangles?"},
   opts:{tr:["4 dik açısı vardır","Karşı kenarları paraleldir","Tüm kenarları eşittir","4 kenarlı bir şekildir"],
         ku:["4 goşeyên rast hene","Kêlekên pêşber paralel in","Hemû kêlek wekhev in","Teşeya 4-kêlek e"],
         en:["Has 4 right angles","Opposite sides parallel","All sides equal","Has 4 sides"]},
   correct:2,
   hint:{tr:"Karenin tüm kenarları eşit — bu özellik dikdörtgende olmak zorunda değil. Diğer özellikler her iki şekilde de var.",ku:"Hemû kêlekên çaryalî wekhev in — ev taybetmendî di dîkdîortgenê de ne pêwîst e.",en:"Square has all sides equal — this property isn't required for rectangle. Other properties are shared."}},

  // ═══ YENİ L2 ETKİNLİKLERİ ═══
  {id:"l2_h",phase:"IN",level:2,icon:"⚖️",
   label:{tr:"Gerek ve Yeter",ku:"Pêwîst û Têr",en:"Necessary & Sufficient"},
   q:{tr:"'Bir dörtgenin tüm kenarları eşitse' o dörtgenin eşkenar dörtgen olması için:",ku:"'Heke hemû kêlekên çarhêlê wekhev bin' ew dibe lozeng?",en:"'If a quadrilateral has all sides equal' for it to be a rhombus, this is:"},
   opts:{tr:["Ne gerek ne yeter koşul","Sadece gerek koşul","Sadece yeter koşul","Hem gerek hem yeter koşul"],
         ku:["Ne mercê pêwîst, ne yê têr","Tenê mercê pêwîst","Tenê mercê têr","Hem mercê pêwîst, hem yê têr"],
         en:["Neither necessary nor sufficient","Only necessary","Only sufficient","Both necessary and sufficient"]},
   correct:3,
   hint:{tr:"Eşkenar dörtgenin tanımı: 4 kenarı eşit dörtgen. Yani bu koşul HEM gereklidir (sağlanmazsa eşkenar dörtgen olamaz) HEM yeterlidir (sağlanırsa kesinlikle eşkenar dörtgendir).",ku:"Danasîna lozengê: çarhêla bi 4 kêlekên wekhev. Ev merc HEM pêwîst e HEM jî têr e.",en:"Definition of rhombus: quadrilateral with 4 equal sides. This condition is BOTH necessary (must hold) AND sufficient (if holds, it IS a rhombus)."}},
  {id:"l2_i",phase:"E",level:2,icon:"🔺",
   label:{tr:"Üçgen Sınıflama",ku:"Polîkirina Sêgoşeyan",en:"Triangle Classification"},
   q:{tr:"Hangisi DOĞRUDUR?",ku:"Kîjan RAST e?",en:"Which is TRUE?"},
   opts:{tr:["Eşkenar üçgen özel bir ikizkenar üçgendir","İkizkenar üçgen özel bir eşkenar üçgendir","Dik üçgen her zaman ikizkenardır","Eşkenar üçgen asla dik olamaz"],
         ku:["Sêgoşeya wekhev cureyek taybet a sêgoşeya dukenar e","Sêgoşeya dukenar cureyek taybet a sêgoşeya wekhev e","Sêgoşeya rast her dem dukenar e","Sêgoşeya wekhev tu car ne rast e"],
         en:["Equilateral is a special isosceles","Isosceles is a special equilateral","Right triangles are always isosceles","Equilateral can never be right"]},
   correct:0,
   hint:{tr:"Eşkenar üçgen ⊂ İkizkenar üçgen. 'En az 2 kenar eşit' = ikizkenar. Eşkenar bunun özel durumu. Eşkenar üçgenin açıları 60° olduğu için dik olamaz (son kısım doğru ama ana iddia 'özel ikizkenar' olmasıdır).",ku:"Sêgoşeya wekhev ⊂ Sêgoşeya dukenar. 'Herî kêm 2 kêlek wekhev' = dukenar. Sêgoşeya wekhev awayekî taybet e.",en:"Equilateral ⊂ Isosceles. 'At least 2 equal sides' = isosceles. Equilateral is a special case."}},
  {id:"l2_j",phase:"IN",level:2,icon:"🧠",
   label:{tr:"Çürüt",ku:"Reşkirin",en:"Counterexample"},
   q:{tr:"'Tüm dörtgenler simetriktir' ifadesini çürütmek için hangi şekil yeterlidir?",ku:"Ji bo reşkirina 'Hemû çarhêl sîmetrîk in' kîjan teşe têrê dike?",en:"Which shape disproves 'All quadrilaterals are symmetric'?"},
   opts:{tr:["Genel yamuk (ikizkenar olmayan)","Kare","Dikdörtgen","Eşkenar dörtgen"],
         ku:["Trapezîdê giştî (ne-dukenar)","Çaryalî","Dîkdîortgen","Lozeng"],
         en:["Scalene trapezoid","Square","Rectangle","Rhombus"]},
   correct:0,
   hint:{tr:"Bir ifadeyi çürütmek için TEK bir karşı örnek yeter. İkizkenar olmayan yamuğun hiçbir simetri ekseni yok — yani dörtgenlerin hepsinin simetrik olmadığını kanıtlar.",ku:"Ji bo reşkirina îdîayê YEK mînaka berevajî têrê dike.",en:"ONE counterexample is enough to disprove. A scalene trapezoid has no symmetry — proves not all quadrilaterals are symmetric."}},
];
